---
permalink: /blog/:categories/:year/:month/:day/:title.html
url: http://facebook.github.io/fresco
name: Fresco
relative_permalinks: false
description: An image management library.
timezone: America/Los_Angeles

safe: true
lsi: false
highlighter: pygments
current_version: 0.9.0

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true
