---
permalink: /blog/:categories/:year/:month/:day/:title.html
url: "http://frescolib.org"
baseurl: ""
name: Fresco
relative_permalinks: false
description: An image management library.
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
highlighter: rouge

safe: true
lsi: false
current_version: 0.9.0

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true
